html-tables
John-bess4/c0523-code-solutions pull request #15
Opened 2023-05-16 14:31 UTC by John-bess4

<img width="771" alt="Screen Shot 2023-05-16 at 7 30 25 AM" src="https://github.com/John-bess4/c0523-code-solutions/assets/126554940/d142eefe-5fd7-45c2-81b4-1e07e6818172">

2023-05-17 16:49 UTC, shawnkost requested changes
Some changes requested here John!

2023-05-17 16:49 UTC, shawnkost commented on html-tables/index.html
> +    <title></title>
The name of the exercise needs to go here!

2023-05-17 16:49 UTC, shawnkost commented on html-tables/index.html
> +          <th scope="row">Grace Hopper</th>
This should be a `td` element

2023-05-17 16:49 UTC, shawnkost commented on html-tables/index.html
> +          <th scope="row">Alan Turing</th>
This should be a `td` element

2023-05-17 16:49 UTC, shawnkost commented on html-tables/index.html
> +          <th scope="row">Douglas Crockford</th>
This should be a `td` element

2023-05-17 16:49 UTC, shawnkost commented on html-tables/index.html
> +          <th scope="row">Tim Berners-Lee</th>
This should be a `td` element

2023-05-17 16:49 UTC, shawnkost commented on html-tables/index.html
> +          <th scope="row">Linus Torvalds</th>
This should be a `td` element

2023-05-18 17:57 UTC, merged

2023-05-28 23:49 UTC, John-bess4 commented
<img width="778" alt="Screen Shot 2023-05-28 at 4 48 55 PM" src="https://github.com/John-bess4/c0523-code-solutions/assets/126554940/c538fc29-0ac4-4e41-898a-42c99f27a837">


Fixed the TH and TD issues and also fixed the title issue as well.